### PR TITLE
Add details to card

### PR DESCRIPTION
**Pull request by elvinvalentino**

### CODE REVIEW

**Comment by rickt25** [comment]
### Potential Bug :
Premiered Video is labeled as Members only stream.

Screen Shot 2022-07-24 at 21 21 08
Screen Shot 2022-07-24 at 21 20 32 (2)



### Expected Result :
Label the video as "PREMIERE"

### Potential Fix :
In comparison to Kureiji Ollie's actual member stream running api data is
```json
{
	"id": "IO_bUr0b_80",
	"title": "【ZOMILY】SO MANY THINGS ARE HAPPENING【Hololive Indonesia 2nd Generation】",
	"type": "stream",
	"topic_id": "membersonly",
	"published_at": "2022-07-24T12:34:33.000Z",
	"available_at": "2022-07-24T13:02:26.000Z",
	"duration": 0,
	"status": "live",
	"start_scheduled": "2022-07-24T12:59:58.000Z",
	"start_actual": "2022-07-24T13:02:26.000Z",
	"live_viewers": 0,
	...
```
and Takanashi Kiara's current premiere stream.
```json
{
	"id": "rHMZxQxnp8Q",
	"title": "【#Kiara3DBirbday】3D Birthday Concert! ✨DIRECTOR'S CUT✨",
	"type": "stream",
	"topic_id": "Birthday",
	"published_at": "2022-07-24T14:00:13.000Z",
	"available_at": "2022-07-24T14:00:13.000Z",
	"duration": 4262,
	"status": "live",
	"live_tl_count": {
		"es": 4
	},
	"start_scheduled": "2022-07-24T14:00:00.000Z",
	"start_actual": "2022-07-24T14:00:13.000Z",
	"live_viewers": 0,
	"recent_live_tls": [
		"es"
	],
	...
```
The duration of a membership stream is always 0, so for a membership stream should have 1 more condition which is the duration has to be 0.

**Comment by andrianwinata** [comment]
> 

ini kalian napain anjirr

**Comment by rickt25** [comment]
> ini kalian napain anjirr

This is a PR Review, please refrain from bringing unrelated topic.

`CANDA CANDA`

**Comment by elvinvalentino** [comment]
should be API problem (?) why the live viewers still count as 0 even tho there is actually 3k people wathing it on yt

**Comment by rickt25** [comment]
I think premiere live videos works differently. I viewed the official https://holodex.net labels it as "Live Now" without the viewer count.

**Comment by andrianwinata** [comment]
yeah, i think so too

**Comment by elvinvalentino** [comment]
> I think premiere live videos works differently. I viewed the official https://holodex.net labels it as "Live Now" without the viewer count.

i think they will hide the viewer.  if the api return 0

**Comment by rickt25** [comment]
LGTM ! thank you 👍

**Pull request merged**
